version: "3.7"

services:

  claim-parser:
    image: aazayats/claim-parser:latest
    command: watch
    restart: always
    env_file:
      - env/claim-parser.env
    networks:
      - local
    volumes:
      - /Users/alexis/workspace/quartex/claim-parser/data:/data/events

networks:
  local: